# Makefile for compiling sitaamirasyarifah.c to sitaamirasyarifah
# Compiler
CC = gcc

# Compiler flags
CFLAGS = -Wall

# Source file
SRC = sitaamirasyarifah.c

# Output file
OUT = sitaamirasyarifah

# Default target
all: $(OUT)

# Compile the source file
$(OUT): $(SRC)
	$(CC) $(CFLAGS) -o $(OUT) $(SRC)

# Clean up compiled files
clean:
	rm -f $(OUT)

